karyotype = primary.karyotype.txt 
chromosomes_units = 100000


<ideogram>
<spacing>
default = 0.005r
  <pairwise chr25 chr1>
   spacing = 10r
  </pairwise>

</spacing>


radius           = 0.90r
thickness        = 40p
fill             = yes
stroke_color     = dgrey
stroke_thickness = 2p

show_label = yes
label_font = default
label_size = 64
label_radius = dims(ideogram,radius) + 0.05r
label_parallel = yes
</ideogram>


<image>
<<include etc/image.conf>>
angle_offset* = -82
</image>


<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>

