show_ticks          = yes
show_tick_labels    = no

<ticks>

radius           = 1r
color            = black
thickness        = 2p
#multiplier       = 1e-6
format           = %d

<tick>
spacing        = 1u
size           = 5p
</tick>

<tick>
spacing        = 5u
size           = 5p
show_label     = yes
label_size     = 5p
label_offset   = 5p
format         = %d
</tick>

</ticks>

